"""Abstract contract for persisting and retrieving signal definitions.

BaseSignalDefinitionRepository defines the persistence boundary for the
Signal Detection Engine. It stores signal definitions only — no market
data, and no evaluation logic. No business rules live here either
(duplicate-name prevention, maximum condition count): mirrors
`app.repositories.screening.repository.BaseScreeningRepository`'s exact
division of responsibility — those rules live in
`app.signals.engine.SignalDetectionService`, the sole Application-layer
service. Every mutating method targeting an existing definition returns
`None` when it does not exist, rather than raising.
"""

from __future__ import annotations

from abc import ABC, abstractmethod

from app.signals.models import SignalDefinition

__all__ = ["BaseSignalDefinitionRepository"]


class BaseSignalDefinitionRepository(ABC):
    """Abstract base class every signal definition repository implementation must inherit."""

    @abstractmethod
    async def create_signal_definition(self, definition: SignalDefinition) -> SignalDefinition:
        """Persist a new definition. `definition.id` is assumed unique — the
        caller (`SignalDetectionService`) is responsible for generating it."""
        raise NotImplementedError

    @abstractmethod
    async def update_signal_definition(self, definition: SignalDefinition) -> SignalDefinition | None:
        """Replace the stored state of the definition with id
        `definition.id`, returning its new state, or `None` if it does not exist."""
        raise NotImplementedError

    @abstractmethod
    async def delete_signal_definition(self, signal_id: str) -> bool:
        """Delete a definition. Returns whether it existed."""
        raise NotImplementedError

    @abstractmethod
    async def duplicate_signal_definition(
        self, signal_id: str, new_signal_id: str, new_name: str
    ) -> SignalDefinition | None:
        """Copy `signal_id`'s conditions/groups into a new, independent
        definition with id `new_signal_id` and name `new_name`, returning
        it, or `None` if `signal_id` does not exist. `new_signal_id` is
        generated by the caller (`SignalDetectionService`), not invented
        here — mirrors `create_signal_definition`."""
        raise NotImplementedError

    @abstractmethod
    async def list_signal_definitions(self) -> list[SignalDefinition]:
        """Return every stored definition."""
        raise NotImplementedError

    @abstractmethod
    async def get_signal_definition(self, signal_id: str) -> SignalDefinition | None:
        """Retrieve a single definition by id."""
        raise NotImplementedError

    @abstractmethod
    async def health_check(self) -> bool:
        """Report whether the underlying storage backend is reachable."""
        raise NotImplementedError
