/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../pages/__root'
import { Route as AuthenticatedRouteImport } from './../pages/_authenticated'
import { Route as ForbiddenRouteImport } from './../pages/forbidden'
import { Route as LoginRouteImport } from './../pages/login'
import { Route as UnauthorizedRouteImport } from './../pages/unauthorized'
import { Route as AuthenticatedIndexRouteImport } from './../pages/_authenticated/index'
import { Route as AuthenticatedDecisionsIndexRouteImport } from './../pages/_authenticated/decisions/index'
import { Route as AuthenticatedDecisionsPortfolioIdRouteImport } from './../pages/_authenticated/decisions/$portfolioId'
import { Route as AuthenticatedGlobalMarketsIndexRouteImport } from './../pages/_authenticated/global-markets/index'
import { Route as AuthenticatedHistoricalAnalysisIndexRouteImport } from './../pages/_authenticated/historical-analysis/index'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './../pages/_authenticated/notifications/index'
import { Route as AuthenticatedProfileIndexRouteImport } from './../pages/_authenticated/profile/index'
import { Route as AuthenticatedResearchIndexRouteImport } from './../pages/_authenticated/research/index'
import { Route as AuthenticatedResearchRequestIdRouteImport } from './../pages/_authenticated/research/$requestId'
import { Route as AuthenticatedResearchBatchRouteImport } from './../pages/_authenticated/research/batch'
import { Route as AuthenticatedResearchCompareRouteImport } from './../pages/_authenticated/research/compare'
import { Route as AuthenticatedScreeningIndexRouteImport } from './../pages/_authenticated/screening/index'
import { Route as AuthenticatedScreeningProfileIdRouteImport } from './../pages/_authenticated/screening/$profileId'
import { Route as AuthenticatedScreeningCompareRouteImport } from './../pages/_authenticated/screening/compare'
import { Route as AuthenticatedSettingsIndexRouteImport } from './../pages/_authenticated/settings/index'
import { Route as AuthenticatedWatchlistsIndexRouteImport } from './../pages/_authenticated/watchlists/index'
import { Route as AuthenticatedWatchlistsWatchlistIdRouteImport } from './../pages/_authenticated/watchlists/$watchlistId'
import { Route as AuthenticatedHistoricalAnalysisBacktestsIndexRouteImport } from './../pages/_authenticated/historical-analysis/backtests/index'
import { Route as AuthenticatedHistoricalAnalysisBacktestsRunIdRouteImport } from './../pages/_authenticated/historical-analysis/backtests/$runId'
import { Route as AuthenticatedHistoricalAnalysisBacktestsCompareRouteImport } from './../pages/_authenticated/historical-analysis/backtests/compare'
import { Route as AuthenticatedHistoricalAnalysisExplainabilityIndexRouteImport } from './../pages/_authenticated/historical-analysis/explainability/index'
import { Route as AuthenticatedHistoricalAnalysisExplainabilityRequestIdRouteImport } from './../pages/_authenticated/historical-analysis/explainability/$requestId'
import { Route as AuthenticatedHistoricalAnalysisExplainabilityCompareRouteImport } from './../pages/_authenticated/historical-analysis/explainability/compare'
import { Route as AuthenticatedScreeningResultsResultIdRouteImport } from './../pages/_authenticated/screening/results/$resultId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDecisionsIndexRoute =
  AuthenticatedDecisionsIndexRouteImport.update({
    id: '/decisions/',
    path: '/decisions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDecisionsPortfolioIdRoute =
  AuthenticatedDecisionsPortfolioIdRouteImport.update({
    id: '/decisions/$portfolioId',
    path: '/decisions/$portfolioId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGlobalMarketsIndexRoute =
  AuthenticatedGlobalMarketsIndexRouteImport.update({
    id: '/global-markets/',
    path: '/global-markets/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHistoricalAnalysisIndexRoute =
  AuthenticatedHistoricalAnalysisIndexRouteImport.update({
    id: '/historical-analysis/',
    path: '/historical-analysis/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResearchIndexRoute =
  AuthenticatedResearchIndexRouteImport.update({
    id: '/research/',
    path: '/research/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResearchRequestIdRoute =
  AuthenticatedResearchRequestIdRouteImport.update({
    id: '/research/$requestId',
    path: '/research/$requestId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResearchBatchRoute =
  AuthenticatedResearchBatchRouteImport.update({
    id: '/research/batch',
    path: '/research/batch',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResearchCompareRoute =
  AuthenticatedResearchCompareRouteImport.update({
    id: '/research/compare',
    path: '/research/compare',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScreeningIndexRoute =
  AuthenticatedScreeningIndexRouteImport.update({
    id: '/screening/',
    path: '/screening/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScreeningProfileIdRoute =
  AuthenticatedScreeningProfileIdRouteImport.update({
    id: '/screening/$profileId',
    path: '/screening/$profileId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScreeningCompareRoute =
  AuthenticatedScreeningCompareRouteImport.update({
    id: '/screening/compare',
    path: '/screening/compare',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWatchlistsIndexRoute =
  AuthenticatedWatchlistsIndexRouteImport.update({
    id: '/watchlists/',
    path: '/watchlists/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWatchlistsWatchlistIdRoute =
  AuthenticatedWatchlistsWatchlistIdRouteImport.update({
    id: '/watchlists/$watchlistId',
    path: '/watchlists/$watchlistId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHistoricalAnalysisBacktestsIndexRoute =
  AuthenticatedHistoricalAnalysisBacktestsIndexRouteImport.update({
    id: '/historical-analysis/backtests/',
    path: '/historical-analysis/backtests/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHistoricalAnalysisBacktestsRunIdRoute =
  AuthenticatedHistoricalAnalysisBacktestsRunIdRouteImport.update({
    id: '/historical-analysis/backtests/$runId',
    path: '/historical-analysis/backtests/$runId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHistoricalAnalysisBacktestsCompareRoute =
  AuthenticatedHistoricalAnalysisBacktestsCompareRouteImport.update({
    id: '/historical-analysis/backtests/compare',
    path: '/historical-analysis/backtests/compare',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHistoricalAnalysisExplainabilityIndexRoute =
  AuthenticatedHistoricalAnalysisExplainabilityIndexRouteImport.update({
    id: '/historical-analysis/explainability/',
    path: '/historical-analysis/explainability/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHistoricalAnalysisExplainabilityRequestIdRoute =
  AuthenticatedHistoricalAnalysisExplainabilityRequestIdRouteImport.update({
    id: '/historical-analysis/explainability/$requestId',
    path: '/historical-analysis/explainability/$requestId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHistoricalAnalysisExplainabilityCompareRoute =
  AuthenticatedHistoricalAnalysisExplainabilityCompareRouteImport.update({
    id: '/historical-analysis/explainability/compare',
    path: '/historical-analysis/explainability/compare',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScreeningResultsResultIdRoute =
  AuthenticatedScreeningResultsResultIdRouteImport.update({
    id: '/screening/results/$resultId',
    path: '/screening/results/$resultId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/decisions/$portfolioId': typeof AuthenticatedDecisionsPortfolioIdRoute
  '/research/$requestId': typeof AuthenticatedResearchRequestIdRoute
  '/research/batch': typeof AuthenticatedResearchBatchRoute
  '/research/compare': typeof AuthenticatedResearchCompareRoute
  '/screening/$profileId': typeof AuthenticatedScreeningProfileIdRoute
  '/screening/compare': typeof AuthenticatedScreeningCompareRoute
  '/watchlists/$watchlistId': typeof AuthenticatedWatchlistsWatchlistIdRoute
  '/decisions/': typeof AuthenticatedDecisionsIndexRoute
  '/global-markets/': typeof AuthenticatedGlobalMarketsIndexRoute
  '/historical-analysis/': typeof AuthenticatedHistoricalAnalysisIndexRoute
  '/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/research/': typeof AuthenticatedResearchIndexRoute
  '/screening/': typeof AuthenticatedScreeningIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/watchlists/': typeof AuthenticatedWatchlistsIndexRoute
  '/historical-analysis/backtests/$runId': typeof AuthenticatedHistoricalAnalysisBacktestsRunIdRoute
  '/historical-analysis/backtests/compare': typeof AuthenticatedHistoricalAnalysisBacktestsCompareRoute
  '/historical-analysis/explainability/$requestId': typeof AuthenticatedHistoricalAnalysisExplainabilityRequestIdRoute
  '/historical-analysis/explainability/compare': typeof AuthenticatedHistoricalAnalysisExplainabilityCompareRoute
  '/screening/results/$resultId': typeof AuthenticatedScreeningResultsResultIdRoute
  '/historical-analysis/backtests/': typeof AuthenticatedHistoricalAnalysisBacktestsIndexRoute
  '/historical-analysis/explainability/': typeof AuthenticatedHistoricalAnalysisExplainabilityIndexRoute
}
export interface FileRoutesByTo {
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/': typeof AuthenticatedIndexRoute
  '/decisions/$portfolioId': typeof AuthenticatedDecisionsPortfolioIdRoute
  '/research/$requestId': typeof AuthenticatedResearchRequestIdRoute
  '/research/batch': typeof AuthenticatedResearchBatchRoute
  '/research/compare': typeof AuthenticatedResearchCompareRoute
  '/screening/$profileId': typeof AuthenticatedScreeningProfileIdRoute
  '/screening/compare': typeof AuthenticatedScreeningCompareRoute
  '/watchlists/$watchlistId': typeof AuthenticatedWatchlistsWatchlistIdRoute
  '/decisions': typeof AuthenticatedDecisionsIndexRoute
  '/global-markets': typeof AuthenticatedGlobalMarketsIndexRoute
  '/historical-analysis': typeof AuthenticatedHistoricalAnalysisIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/research': typeof AuthenticatedResearchIndexRoute
  '/screening': typeof AuthenticatedScreeningIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/watchlists': typeof AuthenticatedWatchlistsIndexRoute
  '/historical-analysis/backtests/$runId': typeof AuthenticatedHistoricalAnalysisBacktestsRunIdRoute
  '/historical-analysis/backtests/compare': typeof AuthenticatedHistoricalAnalysisBacktestsCompareRoute
  '/historical-analysis/explainability/$requestId': typeof AuthenticatedHistoricalAnalysisExplainabilityRequestIdRoute
  '/historical-analysis/explainability/compare': typeof AuthenticatedHistoricalAnalysisExplainabilityCompareRoute
  '/screening/results/$resultId': typeof AuthenticatedScreeningResultsResultIdRoute
  '/historical-analysis/backtests': typeof AuthenticatedHistoricalAnalysisBacktestsIndexRoute
  '/historical-analysis/explainability': typeof AuthenticatedHistoricalAnalysisExplainabilityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/decisions/$portfolioId': typeof AuthenticatedDecisionsPortfolioIdRoute
  '/_authenticated/research/$requestId': typeof AuthenticatedResearchRequestIdRoute
  '/_authenticated/research/batch': typeof AuthenticatedResearchBatchRoute
  '/_authenticated/research/compare': typeof AuthenticatedResearchCompareRoute
  '/_authenticated/screening/$profileId': typeof AuthenticatedScreeningProfileIdRoute
  '/_authenticated/screening/compare': typeof AuthenticatedScreeningCompareRoute
  '/_authenticated/watchlists/$watchlistId': typeof AuthenticatedWatchlistsWatchlistIdRoute
  '/_authenticated/decisions/': typeof AuthenticatedDecisionsIndexRoute
  '/_authenticated/global-markets/': typeof AuthenticatedGlobalMarketsIndexRoute
  '/_authenticated/historical-analysis/': typeof AuthenticatedHistoricalAnalysisIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/research/': typeof AuthenticatedResearchIndexRoute
  '/_authenticated/screening/': typeof AuthenticatedScreeningIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/watchlists/': typeof AuthenticatedWatchlistsIndexRoute
  '/_authenticated/historical-analysis/backtests/$runId': typeof AuthenticatedHistoricalAnalysisBacktestsRunIdRoute
  '/_authenticated/historical-analysis/backtests/compare': typeof AuthenticatedHistoricalAnalysisBacktestsCompareRoute
  '/_authenticated/historical-analysis/explainability/$requestId': typeof AuthenticatedHistoricalAnalysisExplainabilityRequestIdRoute
  '/_authenticated/historical-analysis/explainability/compare': typeof AuthenticatedHistoricalAnalysisExplainabilityCompareRoute
  '/_authenticated/screening/results/$resultId': typeof AuthenticatedScreeningResultsResultIdRoute
  '/_authenticated/historical-analysis/backtests/': typeof AuthenticatedHistoricalAnalysisBacktestsIndexRoute
  '/_authenticated/historical-analysis/explainability/': typeof AuthenticatedHistoricalAnalysisExplainabilityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forbidden'
    | '/login'
    | '/unauthorized'
    | '/decisions/$portfolioId'
    | '/research/$requestId'
    | '/research/batch'
    | '/research/compare'
    | '/screening/$profileId'
    | '/screening/compare'
    | '/watchlists/$watchlistId'
    | '/decisions/'
    | '/global-markets/'
    | '/historical-analysis/'
    | '/notifications/'
    | '/profile/'
    | '/research/'
    | '/screening/'
    | '/settings/'
    | '/watchlists/'
    | '/historical-analysis/backtests/$runId'
    | '/historical-analysis/backtests/compare'
    | '/historical-analysis/explainability/$requestId'
    | '/historical-analysis/explainability/compare'
    | '/screening/results/$resultId'
    | '/historical-analysis/backtests/'
    | '/historical-analysis/explainability/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forbidden'
    | '/login'
    | '/unauthorized'
    | '/'
    | '/decisions/$portfolioId'
    | '/research/$requestId'
    | '/research/batch'
    | '/research/compare'
    | '/screening/$profileId'
    | '/screening/compare'
    | '/watchlists/$watchlistId'
    | '/decisions'
    | '/global-markets'
    | '/historical-analysis'
    | '/notifications'
    | '/profile'
    | '/research'
    | '/screening'
    | '/settings'
    | '/watchlists'
    | '/historical-analysis/backtests/$runId'
    | '/historical-analysis/backtests/compare'
    | '/historical-analysis/explainability/$requestId'
    | '/historical-analysis/explainability/compare'
    | '/screening/results/$resultId'
    | '/historical-analysis/backtests'
    | '/historical-analysis/explainability'
  id:
    | '__root__'
    | '/_authenticated'
    | '/forbidden'
    | '/login'
    | '/unauthorized'
    | '/_authenticated/'
    | '/_authenticated/decisions/$portfolioId'
    | '/_authenticated/research/$requestId'
    | '/_authenticated/research/batch'
    | '/_authenticated/research/compare'
    | '/_authenticated/screening/$profileId'
    | '/_authenticated/screening/compare'
    | '/_authenticated/watchlists/$watchlistId'
    | '/_authenticated/decisions/'
    | '/_authenticated/global-markets/'
    | '/_authenticated/historical-analysis/'
    | '/_authenticated/notifications/'
    | '/_authenticated/profile/'
    | '/_authenticated/research/'
    | '/_authenticated/screening/'
    | '/_authenticated/settings/'
    | '/_authenticated/watchlists/'
    | '/_authenticated/historical-analysis/backtests/$runId'
    | '/_authenticated/historical-analysis/backtests/compare'
    | '/_authenticated/historical-analysis/explainability/$requestId'
    | '/_authenticated/historical-analysis/explainability/compare'
    | '/_authenticated/screening/results/$resultId'
    | '/_authenticated/historical-analysis/backtests/'
    | '/_authenticated/historical-analysis/explainability/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/decisions/': {
      id: '/_authenticated/decisions/'
      path: '/decisions'
      fullPath: '/decisions/'
      preLoaderRoute: typeof AuthenticatedDecisionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/decisions/$portfolioId': {
      id: '/_authenticated/decisions/$portfolioId'
      path: '/decisions/$portfolioId'
      fullPath: '/decisions/$portfolioId'
      preLoaderRoute: typeof AuthenticatedDecisionsPortfolioIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/global-markets/': {
      id: '/_authenticated/global-markets/'
      path: '/global-markets'
      fullPath: '/global-markets/'
      preLoaderRoute: typeof AuthenticatedGlobalMarketsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/historical-analysis/': {
      id: '/_authenticated/historical-analysis/'
      path: '/historical-analysis'
      fullPath: '/historical-analysis/'
      preLoaderRoute: typeof AuthenticatedHistoricalAnalysisIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/research/': {
      id: '/_authenticated/research/'
      path: '/research'
      fullPath: '/research/'
      preLoaderRoute: typeof AuthenticatedResearchIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/research/$requestId': {
      id: '/_authenticated/research/$requestId'
      path: '/research/$requestId'
      fullPath: '/research/$requestId'
      preLoaderRoute: typeof AuthenticatedResearchRequestIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/research/batch': {
      id: '/_authenticated/research/batch'
      path: '/research/batch'
      fullPath: '/research/batch'
      preLoaderRoute: typeof AuthenticatedResearchBatchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/research/compare': {
      id: '/_authenticated/research/compare'
      path: '/research/compare'
      fullPath: '/research/compare'
      preLoaderRoute: typeof AuthenticatedResearchCompareRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/screening/': {
      id: '/_authenticated/screening/'
      path: '/screening'
      fullPath: '/screening/'
      preLoaderRoute: typeof AuthenticatedScreeningIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/screening/$profileId': {
      id: '/_authenticated/screening/$profileId'
      path: '/screening/$profileId'
      fullPath: '/screening/$profileId'
      preLoaderRoute: typeof AuthenticatedScreeningProfileIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/screening/compare': {
      id: '/_authenticated/screening/compare'
      path: '/screening/compare'
      fullPath: '/screening/compare'
      preLoaderRoute: typeof AuthenticatedScreeningCompareRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/watchlists/': {
      id: '/_authenticated/watchlists/'
      path: '/watchlists'
      fullPath: '/watchlists/'
      preLoaderRoute: typeof AuthenticatedWatchlistsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/watchlists/$watchlistId': {
      id: '/_authenticated/watchlists/$watchlistId'
      path: '/watchlists/$watchlistId'
      fullPath: '/watchlists/$watchlistId'
      preLoaderRoute: typeof AuthenticatedWatchlistsWatchlistIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/historical-analysis/backtests/': {
      id: '/_authenticated/historical-analysis/backtests/'
      path: '/historical-analysis/backtests'
      fullPath: '/historical-analysis/backtests/'
      preLoaderRoute: typeof AuthenticatedHistoricalAnalysisBacktestsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/historical-analysis/backtests/$runId': {
      id: '/_authenticated/historical-analysis/backtests/$runId'
      path: '/historical-analysis/backtests/$runId'
      fullPath: '/historical-analysis/backtests/$runId'
      preLoaderRoute: typeof AuthenticatedHistoricalAnalysisBacktestsRunIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/historical-analysis/backtests/compare': {
      id: '/_authenticated/historical-analysis/backtests/compare'
      path: '/historical-analysis/backtests/compare'
      fullPath: '/historical-analysis/backtests/compare'
      preLoaderRoute: typeof AuthenticatedHistoricalAnalysisBacktestsCompareRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/historical-analysis/explainability/': {
      id: '/_authenticated/historical-analysis/explainability/'
      path: '/historical-analysis/explainability'
      fullPath: '/historical-analysis/explainability/'
      preLoaderRoute: typeof AuthenticatedHistoricalAnalysisExplainabilityIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/historical-analysis/explainability/$requestId': {
      id: '/_authenticated/historical-analysis/explainability/$requestId'
      path: '/historical-analysis/explainability/$requestId'
      fullPath: '/historical-analysis/explainability/$requestId'
      preLoaderRoute: typeof AuthenticatedHistoricalAnalysisExplainabilityRequestIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/historical-analysis/explainability/compare': {
      id: '/_authenticated/historical-analysis/explainability/compare'
      path: '/historical-analysis/explainability/compare'
      fullPath: '/historical-analysis/explainability/compare'
      preLoaderRoute: typeof AuthenticatedHistoricalAnalysisExplainabilityCompareRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/screening/results/$resultId': {
      id: '/_authenticated/screening/results/$resultId'
      path: '/screening/results/$resultId'
      fullPath: '/screening/results/$resultId'
      preLoaderRoute: typeof AuthenticatedScreeningResultsResultIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDecisionsPortfolioIdRoute: typeof AuthenticatedDecisionsPortfolioIdRoute
  AuthenticatedResearchRequestIdRoute: typeof AuthenticatedResearchRequestIdRoute
  AuthenticatedResearchBatchRoute: typeof AuthenticatedResearchBatchRoute
  AuthenticatedResearchCompareRoute: typeof AuthenticatedResearchCompareRoute
  AuthenticatedScreeningProfileIdRoute: typeof AuthenticatedScreeningProfileIdRoute
  AuthenticatedScreeningCompareRoute: typeof AuthenticatedScreeningCompareRoute
  AuthenticatedWatchlistsWatchlistIdRoute: typeof AuthenticatedWatchlistsWatchlistIdRoute
  AuthenticatedDecisionsIndexRoute: typeof AuthenticatedDecisionsIndexRoute
  AuthenticatedGlobalMarketsIndexRoute: typeof AuthenticatedGlobalMarketsIndexRoute
  AuthenticatedHistoricalAnalysisIndexRoute: typeof AuthenticatedHistoricalAnalysisIndexRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedResearchIndexRoute: typeof AuthenticatedResearchIndexRoute
  AuthenticatedScreeningIndexRoute: typeof AuthenticatedScreeningIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedWatchlistsIndexRoute: typeof AuthenticatedWatchlistsIndexRoute
  AuthenticatedHistoricalAnalysisBacktestsRunIdRoute: typeof AuthenticatedHistoricalAnalysisBacktestsRunIdRoute
  AuthenticatedHistoricalAnalysisBacktestsCompareRoute: typeof AuthenticatedHistoricalAnalysisBacktestsCompareRoute
  AuthenticatedHistoricalAnalysisExplainabilityRequestIdRoute: typeof AuthenticatedHistoricalAnalysisExplainabilityRequestIdRoute
  AuthenticatedHistoricalAnalysisExplainabilityCompareRoute: typeof AuthenticatedHistoricalAnalysisExplainabilityCompareRoute
  AuthenticatedScreeningResultsResultIdRoute: typeof AuthenticatedScreeningResultsResultIdRoute
  AuthenticatedHistoricalAnalysisBacktestsIndexRoute: typeof AuthenticatedHistoricalAnalysisBacktestsIndexRoute
  AuthenticatedHistoricalAnalysisExplainabilityIndexRoute: typeof AuthenticatedHistoricalAnalysisExplainabilityIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDecisionsPortfolioIdRoute:
    AuthenticatedDecisionsPortfolioIdRoute,
  AuthenticatedResearchRequestIdRoute: AuthenticatedResearchRequestIdRoute,
  AuthenticatedResearchBatchRoute: AuthenticatedResearchBatchRoute,
  AuthenticatedResearchCompareRoute: AuthenticatedResearchCompareRoute,
  AuthenticatedScreeningProfileIdRoute: AuthenticatedScreeningProfileIdRoute,
  AuthenticatedScreeningCompareRoute: AuthenticatedScreeningCompareRoute,
  AuthenticatedWatchlistsWatchlistIdRoute:
    AuthenticatedWatchlistsWatchlistIdRoute,
  AuthenticatedDecisionsIndexRoute: AuthenticatedDecisionsIndexRoute,
  AuthenticatedGlobalMarketsIndexRoute: AuthenticatedGlobalMarketsIndexRoute,
  AuthenticatedHistoricalAnalysisIndexRoute:
    AuthenticatedHistoricalAnalysisIndexRoute,
  AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedResearchIndexRoute: AuthenticatedResearchIndexRoute,
  AuthenticatedScreeningIndexRoute: AuthenticatedScreeningIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedWatchlistsIndexRoute: AuthenticatedWatchlistsIndexRoute,
  AuthenticatedHistoricalAnalysisBacktestsRunIdRoute:
    AuthenticatedHistoricalAnalysisBacktestsRunIdRoute,
  AuthenticatedHistoricalAnalysisBacktestsCompareRoute:
    AuthenticatedHistoricalAnalysisBacktestsCompareRoute,
  AuthenticatedHistoricalAnalysisExplainabilityRequestIdRoute:
    AuthenticatedHistoricalAnalysisExplainabilityRequestIdRoute,
  AuthenticatedHistoricalAnalysisExplainabilityCompareRoute:
    AuthenticatedHistoricalAnalysisExplainabilityCompareRoute,
  AuthenticatedScreeningResultsResultIdRoute:
    AuthenticatedScreeningResultsResultIdRoute,
  AuthenticatedHistoricalAnalysisBacktestsIndexRoute:
    AuthenticatedHistoricalAnalysisBacktestsIndexRoute,
  AuthenticatedHistoricalAnalysisExplainabilityIndexRoute:
    AuthenticatedHistoricalAnalysisExplainabilityIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
