import { Fragment, useMemo, useState, type ReactNode } from "react";
import { Badge } from "@/components/badge";
import { AssetFreshnessNote } from "@/features/global-markets/data-freshness-badge";
import type { RankedAsset, RankingFactor, RiskClassification } from "@/types/global-markets";

type SortField = "rank" | "ticker" | "final_score";

/** Never implies fraud/manipulation — same terminology discipline
 * `RiskClassification`'s own backend docstring requires, just rendered
 * as a readable label instead of the raw enum member. */
const RISK_LABELS: Record<RiskClassification, string> = {
  STRONG_MOMENTUM_LOWER_RISK: "Strong momentum, lower risk",
  STRONG_MOMENTUM_MODERATE_RISK: "Strong momentum, moderate risk",
  STRONG_MOMENTUM_HIGH_RISK: "Strong momentum, high risk",
  EXTREME_MOMENTUM_EXTREME_RISK: "Extreme momentum, extreme risk",
  MODERATE_MOMENTUM: "Moderate momentum",
  WEAK_MOMENTUM: "Weak momentum",
  INSUFFICIENT_CONFIDENCE: "Insufficient data confidence",
};

/** Human-readable labels for every `RankingFactor` — see that type's own
 * backend docstring (`app.global_markets.ranking.models`) for what each
 * one actually measures. Every factor score is always shown (never
 * hidden), matching the backend's own "no hidden weighting, every
 * contribution inspectable" requirement. */
const FACTOR_LABELS: Record<RankingFactor, string> = {
  PRICE_PERFORMANCE: "Price performance",
  MOMENTUM: "Momentum",
  VOLUME_LIQUIDITY: "Volume / liquidity",
  VOLATILITY: "Volatility",
  MARKET_CAP: "Market cap",
  RISK: "Risk (higher = safer)",
  SOURCE_CONFIDENCE: "Source confidence",
  DATA_FRESHNESS: "Data freshness",
  CROSS_SOURCE_AGREEMENT: "Cross-source agreement",
  NEWS_EVENT_IMPACT: "News/event impact",
  TECHNICAL_SIGNAL: "Technical signal",
  FUNDAMENTAL_SIGNAL: "Fundamental signal",
};

function formatPrice(price: number | null, currency: string | null): string {
  if (price === null) return "—";
  return currency ? `${currency} ${price.toLocaleString(undefined, { maximumFractionDigits: 4 })}` : price.toLocaleString();
}

function formatMarketCap(marketCap: number | null): string {
  if (marketCap === null) return "—";
  if (marketCap >= 1e12) return `${(marketCap / 1e12).toFixed(2)}T`;
  if (marketCap >= 1e9) return `${(marketCap / 1e9).toFixed(2)}B`;
  if (marketCap >= 1e6) return `${(marketCap / 1e6).toFixed(2)}M`;
  return marketCap.toLocaleString();
}

/**
 * The Top-N (15 main categories, 20 penny/micro-cap) ranked-asset list
 * for one report category — fixed-size and returned unpaginated by
 * `GET .../ranked-assets` (page_size 100 always covers it, see
 * `services/api/global-markets-api.ts`), so — like
 * `ScreeningResultsTable`'s own documented exception — sorting here is a
 * deliberate frontend computation with no server-side equivalent to
 * defer to, but pagination itself is never needed.
 *
 * Each row expands (one at a time) to show its own factor-score
 * breakdown and, when the category's narrative report covered this
 * ticker, its per-asset commentary — both already computed/generated by
 * the backend but previously discarded by this table.
 */
export function RankedAssetTable({
  assets,
  commentaryByTicker,
}: {
  assets: RankedAsset[];
  commentaryByTicker?: Map<string, string> | undefined;
}): ReactNode {
  const [sortField, setSortField] = useState<SortField>("rank");
  const [sortDesc, setSortDesc] = useState(false);
  const [expandedTicker, setExpandedTicker] = useState<string | null>(null);

  const showRiskColumn = assets.some((asset) => asset.risk_classification !== null);
  const columnCount = showRiskColumn ? 7 : 6;

  const sorted = useMemo(() => {
    const copy = [...assets];
    copy.sort((a, b) => {
      const comparison =
        sortField === "rank"
          ? a.rank - b.rank
          : sortField === "final_score"
            ? a.final_score - b.final_score
            : a.snapshot.ticker.localeCompare(b.snapshot.ticker);
      return sortDesc ? -comparison : comparison;
    });
    return copy;
  }, [assets, sortField, sortDesc]);

  function toggleSort(field: SortField): void {
    if (field === sortField) {
      setSortDesc((prev) => !prev);
    } else {
      setSortField(field);
      setSortDesc(field !== "rank");
    }
  }

  function toggleExpanded(ticker: string): void {
    setExpandedTicker((prev) => (prev === ticker ? null : ticker));
  }

  return (
    <div className="overflow-x-auto">
      <table className="w-full text-sm">
        <caption className="sr-only">Ranked assets</caption>
        <thead>
          <tr className="border-b border-slate-200 dark:border-slate-800">
            <SortHeader label="Rank" field="rank" active={sortField} desc={sortDesc} onSort={toggleSort} />
            <SortHeader label="Ticker" field="ticker" active={sortField} desc={sortDesc} onSort={toggleSort} />
            <th scope="col" className="px-3 py-2 text-left text-xs font-semibold text-slate-500 dark:text-slate-400">
              Price
            </th>
            <th scope="col" className="px-3 py-2 text-left text-xs font-semibold text-slate-500 dark:text-slate-400">
              Market cap
            </th>
            <SortHeader label="Score" field="final_score" active={sortField} desc={sortDesc} onSort={toggleSort} />
            {showRiskColumn && (
              <th scope="col" className="px-3 py-2 text-left text-xs font-semibold text-slate-500 dark:text-slate-400">
                Risk classification
              </th>
            )}
            <th scope="col" className="px-3 py-2 text-left text-xs font-semibold text-slate-500 dark:text-slate-400">
              <span className="sr-only">Details</span>
            </th>
          </tr>
        </thead>
        <tbody>
          {sorted.map((asset) => {
            const ticker = asset.snapshot.ticker;
            const isExpanded = expandedTicker === ticker;
            const commentary = commentaryByTicker?.get(ticker);
            const detailId = `ranked-asset-detail-${ticker}`;
            return (
              <Fragment key={ticker}>
                <tr className="border-b border-slate-100 align-top dark:border-slate-800/60">
                  <td className="px-3 py-2 text-slate-500 dark:text-slate-400">{asset.rank}</td>
                  <td className="px-3 py-2">
                    <div className="font-medium text-slate-800 dark:text-slate-200">{ticker}</div>
                    {asset.snapshot.name && <div className="text-xs text-slate-500 dark:text-slate-400">{asset.snapshot.name}</div>}
                  </td>
                  <td className="px-3 py-2 text-slate-700 dark:text-slate-300">{formatPrice(asset.snapshot.price, asset.snapshot.currency)}</td>
                  <td className="px-3 py-2 text-slate-700 dark:text-slate-300">{formatMarketCap(asset.snapshot.market_cap)}</td>
                  <td className="px-3 py-2 text-slate-700 dark:text-slate-300">{asset.final_score.toFixed(1)}</td>
                  {showRiskColumn && (
                    <td className="px-3 py-2">
                      {asset.risk_classification ? <Badge label={RISK_LABELS[asset.risk_classification]} /> : "—"}
                    </td>
                  )}
                  <td className="px-3 py-2">
                    <button
                      type="button"
                      aria-expanded={isExpanded}
                      aria-controls={detailId}
                      onClick={() => {
                        toggleExpanded(ticker);
                      }}
                      className="rounded-md border border-slate-300 px-2 py-1 text-xs font-medium text-slate-700 hover:bg-slate-100 dark:border-slate-700 dark:text-slate-300 dark:hover:bg-slate-800"
                    >
                      {isExpanded ? "Hide" : "Details"}
                    </button>
                  </td>
                </tr>
                {isExpanded && (
                  <tr id={detailId} className="border-b border-slate-100 bg-slate-50 dark:border-slate-800/60 dark:bg-slate-900/40">
                    <td colSpan={columnCount} className="px-3 py-3">
                      <div className="flex flex-col gap-3">
                        <AssetFreshnessNote
                          status={asset.snapshot.provenance.data_freshness_status}
                          sourceTimestamp={asset.snapshot.provenance.source_timestamp}
                        />
                        <div>
                          <h3 className="mb-1.5 text-xs font-semibold text-slate-500 dark:text-slate-400">Factor scores</h3>
                          {asset.factor_scores.length === 0 ? (
                            <p className="text-xs text-slate-500 dark:text-slate-400">No factor scores were computed for this asset.</p>
                          ) : (
                            <ul className="flex flex-col gap-1">
                              {asset.factor_scores.map((factorScore) => (
                                <li key={factorScore.factor} className="flex items-center gap-2 text-xs">
                                  <span className="w-40 shrink-0 text-slate-600 dark:text-slate-300">{FACTOR_LABELS[factorScore.factor]}</span>
                                  <span className="h-1.5 flex-1 max-w-xs rounded-full bg-slate-200 dark:bg-slate-700">
                                    <span
                                      className="block h-1.5 rounded-full bg-brand-600"
                                      style={{ width: `${String(Math.min(100, Math.max(0, factorScore.value)))}%` }}
                                    />
                                  </span>
                                  <span className="w-10 shrink-0 text-right text-slate-500 dark:text-slate-400">{factorScore.value.toFixed(0)}</span>
                                  {factorScore.explanation && (
                                    <span className="text-slate-500 dark:text-slate-400">— {factorScore.explanation}</span>
                                  )}
                                </li>
                              ))}
                            </ul>
                          )}
                        </div>
                        {commentary && (
                          <div>
                            <h3 className="mb-1.5 text-xs font-semibold text-slate-500 dark:text-slate-400">Commentary</h3>
                            <p className="text-xs text-slate-700 dark:text-slate-300">{commentary}</p>
                          </div>
                        )}
                      </div>
                    </td>
                  </tr>
                )}
              </Fragment>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}

function SortHeader({
  label,
  field,
  active,
  desc,
  onSort,
}: {
  label: string;
  field: SortField;
  active: SortField;
  desc: boolean;
  onSort: (field: SortField) => void;
}): ReactNode {
  const isActive = field === active;
  return (
    <th scope="col" aria-sort={isActive ? (desc ? "descending" : "ascending") : "none"} className="px-3 py-2 text-left text-xs font-semibold text-slate-500 dark:text-slate-400">
      <button
        type="button"
        onClick={() => {
          onSort(field);
        }}
        className="flex items-center gap-1 hover:text-slate-900 dark:hover:text-slate-100"
      >
        {label}
        {isActive && <span aria-hidden="true">{desc ? "▼" : "▲"}</span>}
      </button>
    </th>
  );
}
