"""Abstract contract for persisting strategies and strategy evaluation results.

BaseStrategyRepository defines the persistence boundary for the Strategy
Evaluation Engine. It stores strategy definitions and generated evaluation
results only — no market data, no re-derivation of recommendations, and
no business logic (duplicate-name prevention) lives here; that lives in
`app.strategy.engine.StrategyEvaluationService`, the sole
Application-layer service. Every mutating method targeting an existing
record returns `None` when it does not exist, rather than raising —
mirrors every other repository in this codebase.
"""

from __future__ import annotations

from abc import ABC, abstractmethod

from app.strategy.models import InvestmentStrategy, StrategyEvaluationResult

__all__ = ["BaseStrategyRepository"]


class BaseStrategyRepository(ABC):
    """Abstract base class every strategy repository implementation must inherit."""

    @abstractmethod
    async def create_strategy(self, strategy: InvestmentStrategy) -> InvestmentStrategy:
        """Persist a new strategy. `strategy.id` is assumed unique — the
        caller (`StrategyEvaluationService`) is responsible for generating it."""
        raise NotImplementedError

    @abstractmethod
    async def update_strategy(self, strategy: InvestmentStrategy) -> InvestmentStrategy | None:
        """Replace the stored state of the strategy with id `strategy.id`,
        returning its new state, or `None` if it does not exist."""
        raise NotImplementedError

    @abstractmethod
    async def delete_strategy(self, strategy_id: str) -> bool:
        """Delete a strategy. Returns whether it existed."""
        raise NotImplementedError

    @abstractmethod
    async def duplicate_strategy(
        self, strategy_id: str, new_strategy_id: str, new_name: str
    ) -> InvestmentStrategy | None:
        """Copy `strategy_id`'s weightings/rules into a new, independent
        strategy with id `new_strategy_id` and name `new_name`, returning
        it, or `None` if `strategy_id` does not exist. `new_strategy_id`
        is generated by the caller (`StrategyEvaluationService`), not
        invented here — mirrors `create_strategy`."""
        raise NotImplementedError

    @abstractmethod
    async def list_strategies(self) -> list[InvestmentStrategy]:
        """Return every stored strategy."""
        raise NotImplementedError

    @abstractmethod
    async def get_strategy(self, strategy_id: str) -> InvestmentStrategy | None:
        """Retrieve a single strategy by id."""
        raise NotImplementedError

    @abstractmethod
    async def store_evaluation(self, result: StrategyEvaluationResult) -> StrategyEvaluationResult:
        """Persist a generated evaluation result. A request may be
        re-evaluated, producing more than one stored result over time for
        the same `request_id` — see `get_evaluation`."""
        raise NotImplementedError

    @abstractmethod
    async def get_evaluation(self, request_id: str) -> StrategyEvaluationResult | None:
        """Retrieve the most recently stored evaluation result for
        `request_id`, or `None` if none exists."""
        raise NotImplementedError

    @abstractmethod
    async def list_evaluations(self) -> list[StrategyEvaluationResult]:
        """Return every stored evaluation result, across every request."""
        raise NotImplementedError

    @abstractmethod
    async def health_check(self) -> bool:
        """Report whether the underlying storage backend is reachable."""
        raise NotImplementedError
