"""`EventType` — every real-time event this framework can publish."""

from __future__ import annotations

from enum import Enum

__all__ = ["EventType"]


class EventType(str, Enum):
    ALERT_GENERATED = "ALERT_GENERATED"
    BACKTEST_STARTED = "BACKTEST_STARTED"
    BACKTEST_COMPLETED = "BACKTEST_COMPLETED"
    RECOMMENDATION_GENERATED = "RECOMMENDATION_GENERATED"
    STRATEGY_EVALUATION_COMPLETED = "STRATEGY_EVALUATION_COMPLETED"
    RISK_ASSESSMENT_COMPLETED = "RISK_ASSESSMENT_COMPLETED"
    EXPLAINABILITY_COMPLETED = "EXPLAINABILITY_COMPLETED"
    HEALTH_STATUS_CHANGED = "HEALTH_STATUS_CHANGED"
