"""Abstract contract for persisting and retrieving screening profiles.

BaseScreeningRepository defines the persistence boundary for the Screening
Engine. It stores profile *definitions* only — no market data, and no
evaluation logic. No business rules live here either (duplicate-name
prevention, maximum filter count): this sprint's spec lists only two
components to register in the container ("Register repository. Register
ScreeningEngine.") rather than a repository/service pair, so —
unlike `app.repositories.watchlist` — those rules live in
`app.screening.engine.ScreeningEngine` (the sprint's sole Application-layer
service) instead of a separate profile-management service. The repository
itself stays a low-level, permissive persistence boundary: every mutating
method targeting an existing profile returns `None` when it does not
exist, rather than raising (mirrors `BaseWatchlistRepository`).
"""

from __future__ import annotations

from abc import ABC, abstractmethod

from app.screening.models import ScreeningProfile

__all__ = ["BaseScreeningRepository"]


class BaseScreeningRepository(ABC):
    """Abstract base class every screening repository implementation must inherit."""

    @abstractmethod
    async def create_profile(self, profile: ScreeningProfile) -> ScreeningProfile:
        """Persist a new profile. `profile.id` is assumed unique — the
        caller (`ScreeningEngine`) is responsible for generating it."""
        raise NotImplementedError

    @abstractmethod
    async def update_profile(self, profile: ScreeningProfile) -> ScreeningProfile | None:
        """Replace the stored state of the profile with id `profile.id`,
        returning its new state, or `None` if it does not exist."""
        raise NotImplementedError

    @abstractmethod
    async def delete_profile(self, profile_id: str) -> bool:
        """Delete a profile. Returns whether it existed."""
        raise NotImplementedError

    @abstractmethod
    async def list_profiles(self) -> list[ScreeningProfile]:
        """Return every stored profile."""
        raise NotImplementedError

    @abstractmethod
    async def get_profile(self, profile_id: str) -> ScreeningProfile | None:
        """Retrieve a single profile by id."""
        raise NotImplementedError

    @abstractmethod
    async def duplicate_profile(
        self, profile_id: str, new_profile_id: str, new_name: str
    ) -> ScreeningProfile | None:
        """Copy `profile_id`'s filters/groups into a new, independent
        profile with id `new_profile_id` and name `new_name`, returning it,
        or `None` if `profile_id` does not exist. `new_profile_id` is
        generated by the caller (`ScreeningEngine`), not invented here —
        mirrors `create_profile`."""
        raise NotImplementedError

    @abstractmethod
    async def health_check(self) -> bool:
        """Report whether the underlying storage backend is reachable."""
        raise NotImplementedError
