"""Abstract contracts for persisting alert rules and alerts.

Two independent interfaces, `BaseAlertRuleRepository` and
`BaseAlertRepository` — the sprint's own Dependency Injection section
registers "AlertRuleRepository" and "AlertRepository" as two distinct
components, unlike every prior repository sprint (Screening, Signal
Detection, Watchlist), which bundled everything behind one interface. No
business logic lives in either (duplicate-name prevention, maximum rule/
channel counts, cooldown/deduplication) — those live in
`app.alerts.engine.AlertService`, the sole Application-layer service.
Every mutating method targeting an existing record returns `None` when it
does not exist, rather than raising — mirrors every other repository in
this codebase.

Only rules and alerts (generated and suppressed) are stored — no delivery
history exists anywhere in this codebase yet; that is a future sprint's
concern once real notification providers exist.
"""

from __future__ import annotations

from abc import ABC, abstractmethod

from app.alerts.models import Alert, AlertRule

__all__ = ["BaseAlertRuleRepository", "BaseAlertRepository"]


class BaseAlertRuleRepository(ABC):
    """Abstract base class every alert rule repository implementation must inherit."""

    @abstractmethod
    async def create_rule(self, rule: AlertRule) -> AlertRule:
        """Persist a new rule. `rule.id` is assumed unique — the caller
        (`AlertService`) is responsible for generating it."""
        raise NotImplementedError

    @abstractmethod
    async def update_rule(self, rule: AlertRule) -> AlertRule | None:
        """Replace the stored state of the rule with id `rule.id`,
        returning its new state, or `None` if it does not exist."""
        raise NotImplementedError

    @abstractmethod
    async def delete_rule(self, rule_id: str) -> bool:
        """Delete a rule. Returns whether it existed."""
        raise NotImplementedError

    @abstractmethod
    async def duplicate_rule(self, rule_id: str, new_rule_id: str, new_name: str) -> AlertRule | None:
        """Copy `rule_id`'s conditions/policy into a new, independent rule
        with id `new_rule_id` and name `new_name`, returning it, or `None`
        if `rule_id` does not exist. `new_rule_id` is generated by the
        caller (`AlertService`), not invented here — mirrors `create_rule`."""
        raise NotImplementedError

    @abstractmethod
    async def list_rules(self) -> list[AlertRule]:
        """Return every stored rule."""
        raise NotImplementedError

    @abstractmethod
    async def get_rule(self, rule_id: str) -> AlertRule | None:
        """Retrieve a single rule by id."""
        raise NotImplementedError

    @abstractmethod
    async def health_check(self) -> bool:
        """Report whether the underlying storage backend is reachable."""
        raise NotImplementedError


class BaseAlertRepository(ABC):
    """Abstract base class every alert repository implementation must inherit."""

    @abstractmethod
    async def create_alert(self, alert: Alert) -> Alert:
        """Persist a new alert (`GENERATED` or `SUPPRESSED`). `alert.id`
        is assumed unique — the caller (`AlertService`) is responsible for
        generating it."""
        raise NotImplementedError

    @abstractmethod
    async def get_alert(self, alert_id: str) -> Alert | None:
        """Retrieve a single alert by id."""
        raise NotImplementedError

    @abstractmethod
    async def list_alerts(self) -> list[Alert]:
        """Return every stored alert (`GENERATED` and `SUPPRESSED` alike).
        `AlertService` uses this to check cooldown/duplicate state before
        deciding a new evaluation's outcome."""
        raise NotImplementedError

    @abstractmethod
    async def health_check(self) -> bool:
        """Report whether the underlying storage backend is reachable."""
        raise NotImplementedError
